package com.chinasofti.projectDigest.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_lob
 */
public class TLob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lob.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lob.lob
     *
     * @mbg.generated
     */
    private String lob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lob.id
     *
     * @return the value of t_lob.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lob.id
     *
     * @param id the value for t_lob.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lob.lob
     *
     * @return the value of t_lob.lob
     *
     * @mbg.generated
     */
    public String getLob() {
        return lob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lob.lob
     *
     * @param lob the value for t_lob.lob
     *
     * @mbg.generated
     */
    public void setLob(String lob) {
        this.lob = lob == null ? null : lob.trim();
    }
}