package com.chinasofti.projectDigest.dao;

import com.chinasofti.projectDigest.pojo.TLob;
import com.chinasofti.projectDigest.pojo.TLobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    long countByExample(TLobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int deleteByExample(TLobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int insert(TLob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int insertSelective(TLob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    List<TLob> selectByExample(TLobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    TLob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TLob record, @Param("example") TLobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TLob record, @Param("example") TLobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TLob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lob
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TLob record);
}