package com.chinasofti.projectDigest.dao;

import com.chinasofti.projectDigest.pojo.TUserRole;
import com.chinasofti.projectDigest.pojo.TUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	long countByExample(TUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int deleteByExample(TUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int insert(TUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int insertSelective(TUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	List<TUserRole> selectByExample(TUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	TUserRole selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TUserRole record, @Param("example") TUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TUserRole record, @Param("example") TUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TUserRole record);
}